apiVersion: v1
kind: Pod
metadata:
  name: simple-pod  # 파드 이름 설정
  labels:
    app: webui  # 오브젝트 식별하는 레이블 설정
spec:
  containers:
  - name: simple-pod  # 컨테이너 이름 설정, - 은 배열 형태로 묶겠다
    image: arisu1000/simple-container-app  # 컨테이너 사용할 이미지 
---
apiVersion: v1
kind: Service
metadata:
  name: webui  # 파드 이름
spec:
  type: LoadBalancer  # 로드발라스
  selector:
    app: webui  # 오브젝트 식별 레이블
  ports:
  - protocol: TCP
    port: 80  # 외부 포트
    targetPort: 8080  # 컨테이너 포트
    nodePort: 30100  # 노트 포트