apiVersion: v1
kind: Pod
metadata:
  name: git-sync-test
  labels:
    app: webui
spec:
  containers:
  - name: ubuntu
    image: ubuntu:20.04
    args: ['sleep', '100000']
    volumeMounts:
      - mountPath: /git
        name: mygit
  - name: git-sync
    image: k8s.gcr.io/git-sync:v3.1.1
    env:
    - name: GIT_SYNC_REPO  # 싱크할 git 리모트 저장소
      # value: https://github.com/ipcoo43/html_one.git 
      value: https://github.com/ipcoo43/k8s-one.git
    - name: GIT_SYNC_BRANCH  # 어떤 branch를 바라보고 sysnc할지 결정
      value: master
    - name: GIT_SYNC_ROOT  # 내 로컬 어느 위치의 디렉토리에 sysnc를 할지 결정
      value: '/git'
    volumeMounts:
      - mountPath: /git
        name: mygit
  restartPolicy: Never
  # 서로 연결할 volume
  volumes:
    - name: mygit
      emptyDir: {}