apiVersion: v1
kind: ReplicationController
metadata:
  name: pay-rc
spec:
  replicas: 3
  template:
    metadata: 
      labels:
        app: pay
    spec:
      containers:
      - name: pay
        image: smlinux/pay
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pay-service
spec:
  selector:
    app: pay
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080